ProgettoCinema/ProgettoCinema.Web/Models/SalaView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProgettoCinema.Web.Models
{
    public class SalaView
    {
        public int IdSala { get; set; }
        public string NomeFilm { get; set; }

        public string Genere { get; set; }

        public int Durata { get; set; }

        public double Incasso { get; set; }

    }
}

ProgettoCinema/ProgettoCinema.Web/Models/VenditaView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProgettoCinema.Web.Models
{
    public class VenditaView
    {
       
        public string Nome { get; set; }
        public string Cognome { get; set; }

        public DateTime DataDiNascita { get; set; }  
        
        public string Posto { get; set; }

        public double Prezzo { get; set; }

        public Spettatore GetSpettatore()
        {
            return new Spettatore()
            {
                Nome = this.Nome,
                Cognome = this.Cognome,
                DataDiNascita = Convert.ToString(this.DataDiNascita)
            };
        }

        public Biglietto GetBiglietto()
        {
            return new Biglietto()
            {
                Posto=this.Posto,
                Prezzo=this.Prezzo

            };
        }
    }
}

ProgettoCinema/ProgettoCinema.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoCinema.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ProgettoCinema/ProgettoCinema.Web/Controllers/SalaController.cs
using ProgettoCinema.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoCinema.Web.Controllers
{
    public class SalaController : Controller
    {
        private readonly SalaSqlProvider _salaSqlProvider;
        private readonly FilmSqlProvider _filmSqlProvider;
        private readonly BigliettoSqlProvider _bigliettoSqlProvider;
        private readonly SpettatoreSqlProvider _spettatoreSqlProvider;

        public SalaController()
        {
            _salaSqlProvider = new SalaSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _filmSqlProvider = new FilmSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _bigliettoSqlProvider = new BigliettoSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _spettatoreSqlProvider = new SpettatoreSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
        }
        public ActionResult Index()
        {
            var sala = _salaSqlProvider.Get();
            var film = _filmSqlProvider.GetFilter(sala.IdFilmProiettato);

            var salaView = new SalaView()
            {
                IdSala = sala.IdSala,
                NomeFilm = film.Titolo,
                Genere=film.Genere,
                Durata=film.Durata


            };
            return View(salaView);
        }

        public ActionResult SvuotaSala()
        {
            _bigliettoSqlProvider.DeleteAll();
            _spettatoreSqlProvider.DeleteAll();
            return RedirectToAction("Index", "Sala");
        }
        [Route("Sala/GetIncasso/{id}")]
        public ActionResult GetIncasso(string id)
        {
            var biglietti=_bigliettoSqlProvider.GetAll();
            double incasso = 0;
            foreach(var b in biglietti)
            {
                incasso = incasso + b.Prezzo;
            }
            var sala = new SalaView()
            {
                Incasso = incasso,
                IdSala = Convert.ToInt32(id)
            };
            return View(sala);
        }
    }
}

ProgettoCinema/ProgettoCinema.Web/Controllers/VenditaController.cs
using ProgettoCinema.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoCinema.Web.Controllers
{
    public class VenditaController : Controller
    {
        private readonly SpettatoreSqlProvider _spettatoreSqlProvider;
        private readonly BigliettoSqlProvider _bigliettoSqlProvider;
        private readonly SalaSqlProvider _salaSqlProvider;

        public VenditaController()
        {
            _spettatoreSqlProvider = new SpettatoreSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _bigliettoSqlProvider = new BigliettoSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _salaSqlProvider = new SalaSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
        }

       
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(VenditaView vendita)
        {
            
            var biglietti = _bigliettoSqlProvider.GetAll();
            var sala = _salaSqlProvider.Get();

            

            if (biglietti.Count()<=sala.Capienza)
            {
                int posto;
                
                if (biglietti == null)
                {
                    posto = 1;

                }
                else
                {
                    var postoMax = biglietti.Max(n => n.Posto);
                    posto = Convert.ToInt32(postoMax) + 1;

                }

                var biglietto = new Biglietto();
                biglietto.Posto = posto.ToString();

                var spett = vendita.GetSpettatore();
                biglietto.Prezzo = biglietto.GetPrezzoScontato(spett);
                _bigliettoSqlProvider.Insert(biglietto);

                var biglietti2 = _bigliettoSqlProvider.GetAll();
                var id = biglietti2.Max(n => n.IdBiglietto);
                spett.IdBiglietto = id.ToString();
                _spettatoreSqlProvider.Insert(spett);
                return RedirectToAction("Index", "Sala");
            }
            else
            {
                return RedirectToAction("SalaPiena");
            }
           
            
        }

        public ActionResult SalaPiena()
        {
            return View();
        }

        

       

       
    }
}

ProgettoCinema/ProgettoCinema.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProgettoCinema/ProgettoCinema.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProgettoCinema/ProgettoCinema.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ProgettoCinema/ProgettoCinema.Web/Views/Sala/GetIncasso.cshtml
@model ProgettoCinema.Web.Models.SalaView

@{
    ViewBag.Title = "GetPrezzo";
}

<h2>Incasso</h2>

<div>
    <h4>Sala</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdSala)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdSala)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Incasso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Incasso) Euro
        </dd>

    </dl>
</div>

ProgettoCinema/ProgettoCinema.Web/Views/Sala/Index.cshtml
@model ProgettoCinema.Web.Models.SalaView

@{
    ViewBag.Title = "Index";
}

<h2>Sala</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdSala)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeFilm)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genere)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Durata)
        </th>
        <th></th>
    </tr>


    <tr>
        <td>
            @Html.DisplayFor(model => model.IdSala)
        </td>
        <td>
            @Html.DisplayFor(model => model.NomeFilm)
        </td>
        <td>
            @Html.DisplayFor(model => model.Genere)
        </td>
        <td>
            @Html.DisplayFor(model => model.Durata)
        </td>
        <td>
            @Html.ActionLink("Vendi Biglietto", "Create", "Vendita", new { genere = Model.Genere }, null) |
            @Html.ActionLink("Svuota sala", "SvuotaSala") |
            @Html.ActionLink("Incasso sala", "GetIncasso", new { id = Model.IdSala })

        </td>
    </tr>


</table>

ProgettoCinema/ProgettoCinema.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sala cinema", "Index", "Sala", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">              
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProgettoCinema/ProgettoCinema.Web/Views/Vendita/Create.cshtml
@model ProgettoCinema.Web.Models.VenditaView

@{
    ViewBag.Title = "Create";
}

<h2>Inserisci spettatore</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
   
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cognome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cognome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cognome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataDiNascita, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataDiNascita, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataDiNascita, "", new { @class = "text-danger" })
        </div>
    </div>

   



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Acquista" class="btn btn-default" />
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProgettoCinema/ProgettoCinema.Web/Views/Vendita/SalaPiena.cshtml
@{
    ViewBag.Title = "SalaPiena";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Errore</title>
</head>
<body>
    <hgroup>
        <h1></h1>
        <h2>La sala non ha più posti disponibili.</h2>
    </hgroup>
</body>
</html>